import Head from 'next/head';

import { Inter } from '@next/font/google'
import AppContext from '../AppContext/AppContext';
import styles from '../styles/Home.module.css';
import Nav from './components/nav';
import Banner from './components/banner';
import { useContext, useState } from 'react';
import UpcomingEvents from './components/upcomingEvents';
import LatestArticle from './components/latestArticle';
import InboundsTour from './components/inboundsTour';
import Footer from './components/footer';






const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const context = useContext(AppContext);

  let darkMode = context.darkMode;




  return (
    <>
      <Head>
        <title>Travel Gear</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"></link>

      </Head>
      <main className={darkMode ? "dark" : "light"} >

        <Nav darkMode={darkMode}></Nav>
        <Banner></Banner>
        <UpcomingEvents></UpcomingEvents>
        <LatestArticle></LatestArticle>
        <InboundsTour></InboundsTour>
        <Footer></Footer>

      </main>

    </>
  )
}