import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css';
import Nav from './components/nav';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"></link>
      </Head>
      <Nav></Nav>
      <h1 className='text-secondary'>this is akil injamam</h1>
      <h1 className='text-secondary'>this is akil injamam</h1>
      <h1 className='text-secondary'>this is akil injamam</h1>
      <h1 className='text-secondary'>this is akil injamam</h1>
      <h1 className='text-secondary'>this is akil injamam</h1>
      <h1 className='text-secondary'>this is akil injamam</h1>
    </>
  )
}
